### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by azzumaraydid** [syedabdhalim/MRT-OTS#1]
Hai

**Comment by syedabdhalim** [comment]
reopen for testing

**Comment by syedabdhalim** [comment]
https://github.com/syedabdhalim/MRT-OTS/blob/6592baf444fedd962345ac0ca144a14504334d9c/Project2AP/Views/Home/Index.cshtml#L1

Try add comment

**Comment by syedabdhalim** [comment]
fixed
