### ISSUE TITLE
Add sorting function for payment,user and ticket view

### ISSUE THREAD

**Issue by syedabdhalim** [syedabdhalim/MRT-OTS#2]
Add sorting function for payment,user and tickets
@azzumaraydid  

https://github.com/syedabdhalim/MRT-OTS/blob/1a76888a83d66d9b53e3b5b67c0287a98e65bc2b/Project2AP/Controllers/UserController.cs#L141

https://github.com/syedabdhalim/MRT-OTS/blob/1a76888a83d66d9b53e3b5b67c0287a98e65bc2b/Project2AP/Controllers/PaymentController.cs#L22

https://github.com/syedabdhalim/MRT-OTS/blob/1a76888a83d66d9b53e3b5b67c0287a98e65bc2b/Project2AP/Controllers/TicketController.cs#L20

**Comment by sarahdrsam** [comment]
Added sorting function (sort by latest and oldest) for:
- Ticket Report (user and admin)
- Payment Report (user and admin)
- User Report (admin)
