### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by syedabdhalim** [syedabdhalim/MRT-OTS#5]
To @sarahdrsam @azzumaraydid ,

Please do add search function for admin. The purpose of search function is to ease admin to search for data. Instead of reviewing data one by one, admin should be able to view data that he want based on keyword such as email.

**Comment by sarahdrsam** [comment]
Added searching function (search by e-mail) for:
- Ticket Report (admin)
- Payment Report (admin)
- User Report (admin)
